#!/usr/bin/env python3
"""Generate Ansible inventory for every (account, region).

For each account/region it writes  <out>/<account>_<region>.aws_ec2.yml  (an
amazon.aws.aws_ec2 dynamic-inventory config that assumes the account's
AnsibleOpsRole) and a single  <out>/aws_config  containing one AWS CLI profile
per account.  The aws_ssm connection plugin uses those profiles, so the same
cross-account role is used for discovery AND for the SSM sessions.

    python inventory/generate_inventory.py                # accounts.yml only
    python inventory/generate_inventory.py --from-org     # + AWS Organizations
    export AWS_CONFIG_FILE=$PWD/inventory/generated/aws_config
"""
import argparse
import pathlib
import re
import sys

import yaml


def slug(text: str, sep: str = "-") -> str:
    return re.sub(r"[^a-zA-Z0-9]+", sep, text).strip(sep).lower()


def load_accounts(cfg: dict, from_org: bool) -> list:
    accounts = {a["id"]: dict(a) for a in cfg.get("accounts", [])}
    exclude = set(cfg.get("exclude_account_ids", []))
    if from_org:
        import boto3  # imported lazily so the script works offline

        org = boto3.client("organizations")
        for page in org.get_paginator("list_accounts").paginate():
            for acct in page["Accounts"]:
                if acct["Status"] == "ACTIVE":
                    accounts.setdefault(acct["Id"], {"id": acct["Id"], "name": acct["Name"]})
    return [a for a in accounts.values() if a["id"] not in exclude]


def inventory_doc(acct: dict, region: str, cfg: dict) -> dict:
    profile = f"ansible-{slug(acct['name'])}"
    role_arn = f"arn:aws:iam::{acct['id']}:role/{cfg['ops_role_name']}"
    bucket = f"ansible-ssm-{acct['id']}-{region}"
    is_win = "(platform | default('')) == 'windows'"
    return {
        "plugin": "amazon.aws.aws_ec2",
        "regions": [region],
        "assume_role_arn": role_arn,                    # discovery via assumed role
        "filters": {"instance-state-name": "running"},
        "exclude_filters": [{"tag:Monitoring": "disabled"}],   # opt-out tag
        "hostnames": ["instance-id"],                   # aws_ssm needs the instance id
        "compose": {
            "ansible_connection": "'amazon.aws.aws_ssm'",
            "ansible_aws_ssm_profile": f"'{profile}'",
            "ansible_aws_ssm_region": f"'{region}'",
            "ansible_aws_ssm_bucket_name": f"'{bucket}'",
            "ansible_shell_type": f"'powershell' if {is_win} else 'sh'",
            "ansible_become": f"not ({is_win})",
            "aws_account_id": f"'{acct['id']}'",
            "aws_account_name": f"'{acct['name']}'",
        },
        "groups": {
            "linux": f"not ({is_win})",
            "windows": is_win,
            f"account_{slug(acct['name'], '_')}": "true",
        },
        "keyed_groups": [
            {"key": "tags.Environment | default('untagged')", "prefix": "env"},
        ],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--accounts", default="inventory/accounts.yml")
    ap.add_argument("--out", default="inventory/generated")
    ap.add_argument("--aws-config-out", default="inventory/aws_config",
                    help="path for the generated AWS CLI profile file (kept OUTSIDE --out, which Ansible treats as an inventory directory)")
    ap.add_argument("--from-org", action="store_true", help="also discover accounts via AWS Organizations")
    args = ap.parse_args()

    cfg = yaml.safe_load(pathlib.Path(args.accounts).read_text())
    accounts = load_accounts(cfg, args.from_org)
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*.aws_ec2.yml"):        # removed accounts disappear
        stale.unlink()
    stray = out / "aws_config"                     # an older version of this script wrote aws_config
    if stray.exists():                             # HERE, inside the inventory directory Ansible scans;
        stray.unlink()                              # remove it so it's never mistaken for an inventory source.

    profiles, count = [], 0
    for acct in accounts:
        name = slug(acct["name"])
        profiles.append(
            f"[profile ansible-{name}]\n"
            f"role_arn = arn:aws:iam::{acct['id']}:role/{cfg['ops_role_name']}\n"
            f"credential_source = {cfg.get('credential_source', 'Ec2InstanceMetadata')}\n"
            f"role_session_name = ansible-disk-monitoring\n"
        )
        for region in acct.get("regions", cfg["default_regions"]):
            doc = inventory_doc(acct, region, cfg)
            (out / f"{name}_{region}.aws_ec2.yml").write_text(
                "# GENERATED by generate_inventory.py - do not edit\n" + yaml.safe_dump(doc, sort_keys=False)
            )
            count += 1
    aws_config_path = pathlib.Path(args.aws_config_out)
    aws_config_path.parent.mkdir(parents=True, exist_ok=True)
    aws_config_path.write_text("\n".join(profiles))
    print(f"wrote {count} inventory files for {len(accounts)} accounts -> {out}/")
    print(f"next: export AWS_CONFIG_FILE={aws_config_path.resolve()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
